# Generated by Django 5.0.6 on 2024-10-07 01:28

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_tool_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="added_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 7, 1, 28, 33, 279378, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
