# Generated by Django 5.1.1 on 2024-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="tools",
            field=models.ManyToManyField(to="core.tool"),
        ),
    ]
