# Generated by Django 5.1.1 on 2024-10-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_list_tools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="url_github",
            field=models.URLField(unique=True),
        ),
    ]
