# Generated by Django 5.1.1 on 2024-10-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_tool_options_list_created_at_list_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="url_docs",
            field=models.URLField(blank=True),
        ),
    ]
