# Generated by Django 5.1.1 on 2024-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_tool_url_docs"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
