# Generated by Django 5.1.1 on 2024-10-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_tool_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
