# Generated by Django 5.1.2 on 2024-11-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_tool_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="list",
            name="tools",
            field=models.ManyToManyField(related_name="lists", to="core.tool"),
        ),
    ]
