# Generated by Django 5.1.6 on 2025-02-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_tool_archived_alter_list_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="forks",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tool",
            name="stargazers",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
