# Generated by Django 5.2.3 on 2025-07-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_tool_forks_tool_stargazers"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="last_commit_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
